# Use an official Tomcat runtime as a parent image
FROM tomcat:9.0-jdk17-openjdk-slim

# Copy the WAR file to the webapps directory of Tomcat
COPY target/spring-crm-rest.war /usr/local/tomcat/webapps/ROOT.war

# Expose the port your application runs on
EXPOSE 8888

# Start Tomcat
CMD ["catalina.sh", "run"]
